// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: env("postgresql://fantom3527:u1tvXuYbWu9jWMEDCKgX3B4HAtOwBEuc@dpg-d80gbrpo3t8c73do869g-a/example_nxnc"),
  },
});